// <auto-generated />
namespace AlborzNirooEnginesObservationAndMonitoringSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedengineprojectmondemonrels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedengineprojectmondemonrels));
        
        string IMigrationMetadata.Id
        {
            get { return "201901121837090_added-engine-project-mon-demon-rels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
