// <auto-generated />
namespace AlborzNirooEnginesObservationAndMonitoringSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class partnumbersystemm2mrelsetup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(partnumbersystemm2mrelsetup));
        
        string IMigrationMetadata.Id
        {
            get { return "201901111408261_part-number-system-m2m-rel-setup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
