// <auto-generated />
namespace AlborzNirooPartsMonitoringSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedmondemontables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedmondemontables));
        
        string IMigrationMetadata.Id
        {
            get { return "201901121815143_added-mon-demon-tables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
